-keep class * implements com.github.xs93.framework.base.application.IAppLifecycle
-keep class * extends com.github.xs93.framework.base.ui.function.BaseActivityFunction
-keep class * extends com.github.xs93.framework.base.ui.function.BaseFragmentFunction